### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by praneybehl** [nsanden/jvzoo-rest-api-php#1]
Hi there,
Thank you for the work you have put in. Just wondering if it still works.

Thanks

**Comment by nsanden** [comment]
Yep I use it every day.

**Comment by praneybehl** [comment]
Thanks for the reply, if I may, what does the $account_password variable represent? Is it the jvzoo account password?

Secondly, I was wondering if I had to create a REST url to use the API what might that be? As I only get HTML response with a 404 Page.

Any help will be appreciated.
Thanks in advance.
